"""Add email to StudentProfile

Revision ID: 1ad6814b3988
Revises: 4a0a072c2954
Create Date: 2026-10-08 11:00:54.561723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad6814b3988'
down_revision: Union[str, Sequence[str], None] = '4a0a072c2954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'email')
    # ### end Alembic commands ###
