"""add user_id and guest_info to test_attempts

Revision ID: 490901366987
Revises: 9c116ab72275
Create Date: 2026-10-07 18:02:24.006037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490901366987'
down_revision: Union[str, Sequence[str], None] = '9c116ab72275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('test_attempts', sa.Column('guest_info', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'test_attempts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_attempts', type_='foreignkey')
    op.drop_column('test_attempts', 'guest_info')
    op.drop_column('test_attempts', 'user_id')
    # ### end Alembic commands ###
