"""Add missing professional fields

Revision ID: 4a0a072c2954
Revises: 490901366987
Create Date: 2026-10-08 07:14:55.062557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0a072c2954'
down_revision: Union[str, Sequence[str], None] = '490901366987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_appointments', sa.Column('consultation_mode', sa.String(), nullable=True))
    op.add_column('professional_appointments', sa.Column('notes_by_student', sa.Text(), nullable=True))
    op.add_column('professional_appointments', sa.Column('notes_by_admin', sa.Text(), nullable=True))
    op.add_column('professional_appointments', sa.Column('professional_notified_at', sa.DateTime(), nullable=True))
    op.add_column('professional_appointments', sa.Column('student_contact_shared_at', sa.DateTime(), nullable=True))
    op.add_column('professional_appointments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('professional_appointments', sa.Column('cancelled_by', sa.String(), nullable=True))
    op.add_column('professionals', sa.Column('qualification', sa.String(), nullable=True))
    op.add_column('professionals', sa.Column('years_experience_numeric', sa.Integer(), nullable=True))
    op.add_column('professionals', sa.Column('available_days', sa.JSON(), nullable=True))
    op.add_column('professionals', sa.Column('time_slots', sa.JSON(), nullable=True))
    op.add_column('professionals', sa.Column('max_bookings_per_slot', sa.Integer(), nullable=True))
    op.add_column('professionals', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('professionals', sa.Column('consultation_mode', sa.JSON(), nullable=True))
    op.add_column('professionals', sa.Column('languages_spoken', sa.JSON(), nullable=True))
    op.add_column('professionals', sa.Column('location_city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'location_city')
    op.drop_column('professionals', 'languages_spoken')
    op.drop_column('professionals', 'consultation_mode')
    op.drop_column('professionals', 'is_featured')
    op.drop_column('professionals', 'max_bookings_per_slot')
    op.drop_column('professionals', 'time_slots')
    op.drop_column('professionals', 'available_days')
    op.drop_column('professionals', 'years_experience_numeric')
    op.drop_column('professionals', 'qualification')
    op.drop_column('professional_appointments', 'cancelled_by')
    op.drop_column('professional_appointments', 'cancellation_reason')
    op.drop_column('professional_appointments', 'student_contact_shared_at')
    op.drop_column('professional_appointments', 'professional_notified_at')
    op.drop_column('professional_appointments', 'notes_by_admin')
    op.drop_column('professional_appointments', 'notes_by_student')
    op.drop_column('professional_appointments', 'consultation_mode')
    # ### end Alembic commands ###
