"""update_test_models

Revision ID: 8bf8d719feee
Revises: fda82231833f
Create Date: 2026-10-07 12:46:24.134818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bf8d719feee'
down_revision: Union[str, Sequence[str], None] = 'fda82231833f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_profiles', 'location_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('student_profiles', 'preferred_job_location',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='preferred_job_location::json')
    op.add_column('test_attempts', sa.Column('attempt_number', sa.Integer(), nullable=True))
    op.add_column('test_attempts', sa.Column('status', sa.String(), nullable=True))
    op.add_column('test_attempts', sa.Column('max_score', sa.Float(), nullable=True))
    op.add_column('test_attempts', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('test_attempts', sa.Column('is_passed', sa.Boolean(), nullable=True))
    op.add_column('test_attempts', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('test_attempts', sa.Column('section_scores', sa.JSON(), nullable=True))
    op.add_column('test_attempts', sa.Column('certificate_url', sa.String(), nullable=True))
    op.alter_column('test_attempts', 'total_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('test_questions', sa.Column('question_type', sa.String(), nullable=True))
    op.add_column('test_questions', sa.Column('question_image_url', sa.String(), nullable=True))
    op.add_column('test_questions', sa.Column('question_note', sa.Text(), nullable=True))
    op.add_column('test_questions', sa.Column('marks', sa.Float(), nullable=True))
    op.add_column('test_questions', sa.Column('negative_marks', sa.Float(), nullable=True))
    op.add_column('test_questions', sa.Column('time_limit_seconds', sa.Integer(), nullable=True))
    op.add_column('test_questions', sa.Column('section', sa.String(), nullable=True))
    op.add_column('test_questions', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('test_questions', sa.Column('subtopic', sa.String(), nullable=True))
    op.add_column('test_questions', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('test_questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('test_questions', sa.Column('explanation_image_url', sa.String(), nullable=True))
    op.add_column('test_questions', sa.Column('order_index', sa.Integer(), nullable=True))
    op.drop_column('test_questions', 'points')
    op.add_column('tests', sa.Column('test_type', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('category', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('provider_logo_url', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('open_link_token', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('show_result_mode', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('pass_percentage', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('negative_marking', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('negative_marks_per_wrong', sa.Float(), nullable=True))
    op.add_column('tests', sa.Column('shuffle_questions', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('shuffle_options', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('show_answer_after', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('tests', sa.Column('status', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('scheduled_start_at', sa.DateTime(), nullable=True))
    op.add_column('tests', sa.Column('scheduled_end_at', sa.DateTime(), nullable=True))
    op.add_column('tests', sa.Column('certificate_on_pass', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('sections', sa.JSON(), nullable=True))
    op.add_column('tests', sa.Column('created_by_admin_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tests_open_link_token'), 'tests', ['open_link_token'], unique=True)
    op.create_foreign_key(None, 'tests', 'users', ['created_by_admin_id'], ['id'])
    op.drop_column('users', 'goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_index(op.f('ix_tests_open_link_token'), table_name='tests')
    op.drop_column('tests', 'created_by_admin_id')
    op.drop_column('tests', 'sections')
    op.drop_column('tests', 'certificate_on_pass')
    op.drop_column('tests', 'scheduled_end_at')
    op.drop_column('tests', 'scheduled_start_at')
    op.drop_column('tests', 'status')
    op.drop_column('tests', 'instructions')
    op.drop_column('tests', 'show_answer_after')
    op.drop_column('tests', 'shuffle_options')
    op.drop_column('tests', 'shuffle_questions')
    op.drop_column('tests', 'negative_marks_per_wrong')
    op.drop_column('tests', 'negative_marking')
    op.drop_column('tests', 'pass_percentage')
    op.drop_column('tests', 'show_result_mode')
    op.drop_column('tests', 'max_attempts')
    op.drop_column('tests', 'open_link_token')
    op.drop_column('tests', 'is_open')
    op.drop_column('tests', 'provider_logo_url')
    op.drop_column('tests', 'category')
    op.drop_column('tests', 'test_type')
    op.add_column('test_questions', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('test_questions', 'order_index')
    op.drop_column('test_questions', 'explanation_image_url')
    op.drop_column('test_questions', 'explanation')
    op.drop_column('test_questions', 'difficulty')
    op.drop_column('test_questions', 'subtopic')
    op.drop_column('test_questions', 'topic')
    op.drop_column('test_questions', 'section')
    op.drop_column('test_questions', 'time_limit_seconds')
    op.drop_column('test_questions', 'negative_marks')
    op.drop_column('test_questions', 'marks')
    op.drop_column('test_questions', 'question_note')
    op.drop_column('test_questions', 'question_image_url')
    op.drop_column('test_questions', 'question_type')
    op.alter_column('test_attempts', 'total_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('test_attempts', 'certificate_url')
    op.drop_column('test_attempts', 'section_scores')
    op.drop_column('test_attempts', 'started_at')
    op.drop_column('test_attempts', 'is_passed')
    op.drop_column('test_attempts', 'percentage')
    op.drop_column('test_attempts', 'max_score')
    op.drop_column('test_attempts', 'status')
    op.drop_column('test_attempts', 'attempt_number')
    op.alter_column('student_profiles', 'preferred_job_location',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_profiles', 'location_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
