"""Add QuestionTaxonomy table

Revision ID: 9c116ab72275
Revises: e87900ca4ace
Create Date: 2026-10-07 14:28:56.413384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c116ab72275'
down_revision: Union[str, Sequence[str], None] = 'e87900ca4ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_taxonomies',
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_taxonomies_id'), 'question_taxonomies', ['id'], unique=False)
    op.create_index(op.f('ix_question_taxonomies_name'), 'question_taxonomies', ['name'], unique=False)
    op.create_index(op.f('ix_question_taxonomies_type'), 'question_taxonomies', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_taxonomies_type'), table_name='question_taxonomies')
    op.drop_index(op.f('ix_question_taxonomies_name'), table_name='question_taxonomies')
    op.drop_index(op.f('ix_question_taxonomies_id'), table_name='question_taxonomies')
    op.drop_table('question_taxonomies')
    # ### end Alembic commands ###
