"""add default_per_question_seconds

Revision ID: e87900ca4ace
Revises: f3d290252624
Create Date: 2026-10-07 13:27:52.742896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87900ca4ace'
down_revision: Union[str, Sequence[str], None] = 'f3d290252624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('default_per_question_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'default_per_question_seconds')
    # ### end Alembic commands ###
