"""add test_categories

Revision ID: f3d290252624
Revises: 8bf8d719feee
Create Date: 2026-10-07 13:14:00.785919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d290252624'
down_revision: Union[str, Sequence[str], None] = '8bf8d719feee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_categories_id'), 'test_categories', ['id'], unique=False)
    op.create_index(op.f('ix_test_categories_name'), 'test_categories', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_categories_name'), table_name='test_categories')
    op.drop_index(op.f('ix_test_categories_id'), table_name='test_categories')
    op.drop_table('test_categories')
    # ### end Alembic commands ###
