"""verify schema

Revision ID: fda82231833f
Revises: dd9919197247
Create Date: 2026-10-03 20:07:44.258616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fda82231833f'
down_revision: Union[str, Sequence[str], None] = 'dd9919197247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_appointments_id'), table_name='doctor_appointments')
    op.drop_table('doctor_appointments')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_name'), table_name='doctors')
    op.drop_table('doctors')
    op.create_index(op.f('ix_offers_city'), 'offers', ['city'], unique=False)
    op.create_index(op.f('ix_professional_appointments_id'), 'professional_appointments', ['id'], unique=False)
    op.create_index(op.f('ix_professionals_id'), 'professionals', ['id'], unique=False)
    op.create_index(op.f('ix_professionals_name'), 'professionals', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professionals_name'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_id'), table_name='professionals')
    op.drop_index(op.f('ix_professional_appointments_id'), table_name='professional_appointments')
    op.drop_index(op.f('ix_offers_city'), table_name='offers')
    op.create_table('doctors',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specialty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clinic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('consultation_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='doctors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_doctors_name'), 'doctors', ['name'], unique=False)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_table('doctor_appointments',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('appointment_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('appointment_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('doctor_appointments_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('doctor_appointments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_appointments_pkey'))
    )
    op.create_index(op.f('ix_doctor_appointments_id'), 'doctor_appointments', ['id'], unique=False)
    # ### end Alembic commands ###
